name: Deploy static content to Pages

on:
  push:
    branches: ["main"]  # Trigger on push to main branch
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install  # Installs Vite and project dependencies

      - name: Build project
        run: npm run build  # Builds the Vite project (output in `dist` folder by default)

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload built project
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'  # Upload the `dist` directory, Vite's default build output folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
